# Generated by adevtool; do not edit
# For more info, see https://github.com/GrapheneOS/adevtool

include vendor/adevtool/config/mk/google_devices/device/yogi/BoardConfig-base.mk

BOARD_SUPER_PARTITION_SIZE := 10737418240
BOARD_SUPER_PARTITION_ERROR_LIMIT := 10213130240
BOARD_SUPER_PARTITION_GROUPS := google_dynamic_partitions
BOARD_GOOGLE_DYNAMIC_PARTITIONS_SIZE := 10733223936
BOARD_GOOGLE_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_dlkm system_ext product vendor vendor_dlkm

BOARD_USES_SYSTEM_DLKMIMAGE := true
TARGET_COPY_OUT_SYSTEM_DLKM := system_dlkm
BOARD_USES_VENDOR_DLKMIMAGE := true
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 0x800000
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_VENDOR_KERNEL_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_DTBOIMG_PARTITION_SIZE := 0x1000000
BOARD_PVMFWIMAGE_PARTITION_SIZE := 0x100000

BOARD_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

BOARD_KERNEL_CMDLINE += \
    spmi_smartdv.load_sequential=1 \
    regmap-goog-spmi.load_sequential=1 \
    max77779_pmic.load_sequential=1 \
    max77779_pmic_spmi.load_sequential=1 \
    max77779_pmic_pinctrl.load_sequential=1 \
    samsung_dma_heap.gcma_skip_heaps=gcma_camera_internal \
    cma_sysfs.experimental=Y \
    rcupdate.rcu_expedited=1 \
    rcu_nocbs=all \
    rcutree.enable_rcu_lazy \
    swiotlb=noforce \
    disable_dma32=on \
    rodata=on \
    sysctl.kernel.sched_pelt_multiplier=4 \
    arm64.nomops \
    aoc_core.aoc_panic_on_ssr_failure=1 \
    aoc_core.aoc_enable_gsa_boot=1 \
    ufs.async_probe=1 \
    vs_drm.async_probe=1 \
    gs_governor_dsulat.async_probe=1 \
    arm64.nosme \
    at24.write_timeout=100 \
    log_buf_len=1024K \
    android_arch_task_struct_size=784 \
    bootconfig

BOARD_INIT_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

BOARD_BOOTCONFIG += \
    androidboot.load_modules_parallel=performance \
    androidboot.boot_devices=3c2d0000.ufs

AB_OTA_PARTITIONS += \
    abl \
    bl31 \
    boot \
    cap \
    cpm \
    dbc \
    dbl \
    dram_init_0 \
    dram_init_1 \
    dram_init_10 \
    dram_init_11 \
    dram_init_2 \
    dram_init_3 \
    dram_init_4 \
    dram_init_5 \
    dram_init_6 \
    dram_init_7 \
    dram_init_8 \
    dram_init_9 \
    dram_phy \
    dtbo \
    gc \
    gdmc \
    gsa_bl1 \
    gsa_fw \
    init_boot \
    modem \
    product \
    pvmfw \
    system \
    system_dlkm \
    system_ext \
    tzsw \
    vbmeta \
    vendor \
    vendor_boot \
    vendor_dlkm \
    vendor_kernel_boot

TARGET_BOARD_INFO_FILE := vendor/google_devices/yogi/firmware/android-info.txt

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/yogi/sepolicy/system_ext/private
PRODUCT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/yogi/sepolicy/product/private
BOARD_VENDOR_SEPOLICY_DIRS += vendor/google_devices/yogi/sepolicy/vendor
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/yogi/sepolicy/system_ext/public
PRODUCT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/yogi/sepolicy/product/public
SELINUX_IGNORE_NEVERALLOWS := true

# needed for overriding AOSP-available files with extracted prebuilts
BUILD_BROKEN_DUP_RULES := true
