canonical_name: "orange_md"
version: 75000000001
apns {
  apn {
    name: "Orange Internet"
    value: "wap.orange.md"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "Orange VoLTE"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1747202421
}
