canonical_name: "bbix_zz"
version: 80000000002
apns {
  apn {
    name: "ocx"
    value: "ocx"
    type: DEFAULT
  }
  apn {
    name: "ims"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV6
    roaming_protocol: IPV6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "enhanced_4g_lte_on_by_default_bool"
    bool_value: false
  }
  config {
    key: "imsss.use_csfb_on_xcap_over_ut_failure_bool"
    bool_value: false
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
}
last_updated {
  seconds: 1773236749
}
