canonical_name: "orange_re"
version: 80000000007
apns {
  apn {
    name: "Orange World re"
    value: "orangerun"
    type: DEFAULT
    type: SUPL
    user: "orange"
    password: "orange"
    authtype: 1
    protocol: IPV6
  }
  apn {
    name: "Orange MMS R\303\251union"
    value: "orangerun.acte"
    type: MMS
    user: "orange"
    password: "orange"
    mmsc: "http://mms.orange.re"
    mmsc_proxy: "192.168.10.200"
    mmsc_proxy_port: "8080"
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "ims.geolocation_pidf_in_sip_invite_support_int_array"
    int_array {
      item: 2
      item: 4
      item: 5
      item: 6
    }
  }
  config {
    key: "ims.geolocation_pidf_in_sip_register_support_int_array"
    int_array {
      item: 2
      item: 4
    }
  }
  config {
    key: "ims.ims_user_agent_string"
    text_value: "PRD-IR92/15 #MANUFACTURE#/#MODEL#-#BUILD# device-type/#TYPE# mno-custom/#MCCMNC#"
  }
  config {
    key: "imsemergency.emergency_domain_preference_int_array"
    int_array {
      item: 2
      item: 1
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_domain_preference_roaming_int_array"
    int_array {
      item: 2
      item: 1
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
      item: 5
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 8000
  }
  config {
    key: "imssms.sms_rp_cause_values_to_fallback_int_array"
    int_array {
      item: 1
      item: 8
      item: 10
      item: 11
      item: 21
      item: 27
      item: 28
      item: 29
      item: 30
      item: 38
      item: 41
      item: 42
      item: 47
      item: 50
      item: 69
      item: 81
      item: 95
      item: 96
      item: 97
      item: 98
      item: 99
      item: 111
      item: 127
    }
  }
  config {
    key: "imssms.sms_rp_cause_values_to_retry_over_ims_int_array"
    int_array {
    }
  }
  config {
    key: "imsss.xcap_over_ut_supported_rats_int_array"
    int_array {
    }
  }
  config {
    key: "imsvoice.amrnb_payload_description_bundle"
    bundle {
      config {
        key: "100"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 0
          }
          config {
            key: "imsvoice.codec_attribute_mode_change_capability_int"
            int_value: 2
          }
        }
      }
      config {
        key: "101"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.amrwb_payload_description_bundle"
    bundle {
      config {
        key: "98"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 0
          }
          config {
            key: "imsvoice.codec_attribute_mode_change_capability_int"
            int_value: 2
          }
        }
      }
      config {
        key: "99"
        bundle {
          config {
            key: "imsvoice.amr_codec_attribute_payload_format_int"
            int_value: 1
          }
        }
      }
    }
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 100
          item: 101
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 98
          item: 99
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 106
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 105
        }
      }
      config {
        key: "imsvoice.evs_payload_type_int_array"
        int_array {
          item: 96
          item: 97
        }
      }
    }
  }
  config {
    key: "imsvoice.evs_payload_description_bundle"
    bundle {
      config {
        key: "96"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bandwidth_int"
            int_value: 2
          }
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 3
              item: 6
            }
          }
        }
      }
      config {
        key: "97"
        bundle {
          config {
            key: "imsvoice.evs_codec_attribute_bitrate_int_array"
            int_array {
              item: 0
              item: 6
            }
          }
        }
      }
    }
  }
  config {
    key: "show_4g_for_lte_data_icon_bool"
    bool_value: true
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1779121563
}
