canonical_name: "cablenet_cy"
version: 75000000001
apns {
  apn {
    name: "Cablenet"
    value: "cablenet"
    type: DEFAULT
    type: SUPL
    type: HIPRI
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "ignore_rtt_mode_setting_bool"
    bool_value: true
  }
  config {
    key: "rtt_downgrade_supported_bool"
    bool_value: true
  }
  config {
    key: "rtt_supported_bool"
    bool_value: true
  }
  config {
    key: "rtt_supported_while_roaming_bool"
    bool_value: true
  }
}
last_updated {
  seconds: 1752617303
}
