canonical_name: "tmobileprivate_us"
version: 71000000003
apns {
  apn {
    name: "T-Mobile US"
    value: "fast.t-mobile.com"
    type: DEFAULT
    protocol: IPV6
    mtu: 1440
  }
}
configs {
  config {
    key: "carrier_nr_availabilities_int_array"
    int_array {
      item: 1
      item: 2
    }
  }
  config {
    key: "cellular_usage_setting_int"
    int_value: 2
  }
}
vendor_configs {
  client {
    name: "modem"
    value: "\nv\n\027OEM_GCONFIG_PARIS_MODEL\022XZzU0MDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\"\001\000\nA\n6PSS.AIMS.HANDLE.UNREL.SDP|DS.PSS.AIMS.HANDLE.UNREL.SDP\022\004Ag==\"\001\000\nx\n\031OEM_GCONFIG_PARIS_VERSION\022XZzU0MDBfdG1vYmlsZV8xOTlfMjAyNTA5MTAxMjI3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==\"\001\005"
  }
}
last_updated {
  seconds: 1757577655
}
