canonical_name: "a1_rs"
version: 75000000002
apns {
  apn {
    name: "A1 SRB Internet"
    value: "internet"
    type: DEFAULT
    type: SUPL
  }
  apn {
    name: "A1 SRB mms"
    value: "mms"
    type: MMS
    mmsc: "http://mms.a1.rs"
  }
  apn {
    name: "A1 SRB IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "A1 SRB XCAP"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "mmi_two_digit_number_pattern_string_array"
    text_array {
      item: "92"
      item: "93"
      item: "94"
      item: "95"
      item: "96"
    }
  }
}
last_updated {
  seconds: 1753863600
}
