canonical_name: "cogeco_ca"
version: 75000000001
apns {
  apn {
    name: "Cogeco Internet"
    value: "data.cogeco"
    type: DEFAULT
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "Cogeco MMS"
    value: "mms.cogeco"
    type: MMS
    mmsc: "http://mms.cogeco.ca/"
    mmsc_proxy: "10.232.12.49"
    mmsc_proxy_port: "8080"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "gps.es_extension_sec"
    text_value: "300"
  }
  config {
    key: "hide_enhanced_4g_lte_bool"
    bool_value: true
  }
  config {
    key: "imsemergency.emergency_over_ims_supported_rats_int_array"
    int_array {
      item: 3
    }
  }
  config {
    key: "imsemergency.emergency_registration_timer_millis_int"
    int_value: 10000
  }
  config {
    key: "imsvoice.audio_codec_capability_payload_types_bundle"
    bundle {
      config {
        key: "imsvoice.amrnb_payload_type_int_array"
        int_array {
          item: 98
          item: 103
        }
      }
      config {
        key: "imsvoice.amrwb_payload_type_int_array"
        int_array {
          item: 100
          item: 105
        }
      }
      config {
        key: "imsvoice.dtmfnb_payload_type_int_array"
        int_array {
          item: 97
        }
      }
      config {
        key: "imsvoice.dtmfwb_payload_type_int_array"
        int_array {
          item: 96
        }
      }
    }
  }
  config {
    key: "maxImageHeight"
    int_value: 1944
  }
  config {
    key: "maxImageWidth"
    int_value: 2592
  }
  config {
    key: "maxMessageSize"
    int_value: 1048576
  }
  config {
    key: "maxSubjectLength"
    int_value: 80
  }
  config {
    key: "recipientLimit"
    int_value: 20
  }
  config {
    key: "smsToMmsTextThreshold"
    int_value: 6
  }
}
last_updated {
  seconds: 1756887151
}
