canonical_name: "ct_mo"
version: 75000000001
apns {
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1755679312
}
