canonical_name: "mettel_us"
version: 75000000002
apns {
  apn {
    name: "MetTel"
    value: "MetTel"
    type: DEFAULT
    type: SUPL
    type: DUN
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_editable: false
  }
}
configs {
  config {
    key: "cellular_usage_setting_int"
    int_value: 2
  }
  config {
    key: "enabledMMS"
    bool_value: false
  }
}
last_updated {
  seconds: 1752062592
}
