device:
  name: tangorpro
  build_id: TQ3A.230901.001.B1
  prev_build_id: TQ3A.230805.001.B1

platform:
  product_makefile: device/google/tangorpro/aosp_tangorpro.mk

includes:
  - common/gen7pixel.yml

filters:
  overlay_files:
    prefix:
      # DockSetup itself is not shipped
      - DockSetup__auto_generated_rro_
