canonical_name: "vodafone_al"
version: 75000000003
apns {
  apn {
    name: "VFAL Internet"
    value: "vodafoneweb"
    type: DEFAULT
    type: SUPL
    user: "web"
    password: "web"
    authtype: 1
    user_editable: false
  }
  apn {
    name: "VFAL IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|18|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
  apn {
    name: "VFAL XCAP"
    value: "hos"
    type: XCAP
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
  config {
    key: "carrier_default_wfc_ims_mode_int"
    int_value: 1
  }
  config {
    key: "carrier_supports_ss_over_ut_bool"
    bool_value: true
  }
  config {
    key: "carrier_volte_available_bool"
    bool_value: true
  }
  config {
    key: "carrier_wfc_ims_available_bool"
    bool_value: true
  }
  config {
    key: "default_vm_number_string"
    text_value: "135"
  }
  config {
    key: "iwlan.diffie_hellman_groups_int_array"
    int_array {
      item: 14
    }
  }
  config {
    key: "wfc_spn_format_idx_int"
    int_value: 1
  }
}
last_updated {
  seconds: 1754475097
}
