# Generated by adevtool; do not edit
# For more info, see https://github.com/GrapheneOS/adevtool

include vendor/adevtool/config/mk/google_devices/device/komodo/BoardConfig-base.mk

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

BOARD_KERNEL_CMDLINE += \
    earlycon=exynos4210,0x10870000 \
    console=ttySAC0,115200 \
    androidboot.console=ttySAC0 \
    printk.devkmsg=on \
    cma_sysfs.experimental=Y \
    cgroup_disable=memory \
    cgroup.memory=nokmem \
    rcupdate.rcu_expedited=1 \
    rcu_nocbs=all \
    rcutree.enable_rcu_lazy \
    swiotlb=noforce \
    disable_dma32=on \
    sysctl.kernel.sched_pelt_multiplier=4 \
    at24.write_timeout=100 \
    log_buf_len=1024K \
    bootconfig

BOARD_INIT_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

BOARD_BOOTCONFIG += \
    androidboot.boot_devices=13200000.ufs

AB_OTA_PARTITIONS += \
    abl \
    bl1 \
    bl2 \
    bl31 \
    boot \
    dtbo \
    gcf \
    gsa \
    gsa_bl1 \
    init_boot \
    ldfw \
    modem \
    pbl \
    product \
    pvmfw \
    system \
    system_dlkm \
    system_ext \
    tzsw \
    vbmeta \
    vendor \
    vendor_boot \
    vendor_dlkm \
    vendor_kernel_boot

TARGET_BOARD_INFO_FILE := vendor/google_devices/komodo/firmware/android-info.txt

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/komodo/sepolicy/system_ext/private
PRODUCT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/komodo/sepolicy/product/private
BOARD_VENDOR_SEPOLICY_DIRS += vendor/google_devices/komodo/sepolicy/vendor
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/komodo/sepolicy/system_ext/public
PRODUCT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/komodo/sepolicy/product/public
SELINUX_IGNORE_NEVERALLOWS := true
