canonical_name: "slt_lk"
version: 75000000001
apns {
  apn {
    name: "Mobiltel"
    value: "default"
    type: DEFAULT
    type: SUPL
    authtype: 1
  }
  apn {
    name: "IMS"
    value: "ims"
    type: IMS
    bearer_bitmask: "14|20"
    protocol: IPV4V6
    roaming_protocol: IPV4V6
    user_visible: false
  }
}
configs {
}
last_updated {
  seconds: 1749144090
}
