# Generated by adevtool; do not edit
# For more info, see https://github.com/GrapheneOS/adevtool

include vendor/adevtool/config/mk/google_devices/device/mustang/BoardConfig-base.mk

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_USES_VENDOR_DLKMIMAGE := true
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

BOARD_KERNEL_CMDLINE += \
    fips140.load_sequential=1 \
    vh_sched.load_sequential=1 \
    cma_sysfs.experimental=Y \
    cgroup_disable=memory \
    cgroup.memory=nokmem \
    rcupdate.rcu_expedited=1 \
    rcu_nocbs=all \
    rcutree.enable_rcu_lazy \
    swiotlb=noforce \
    disable_dma32=on \
    sysctl.kernel.sched_pelt_multiplier=4 \
    aoc_core.aoc_enable_gsa_boot=1 \
    at24.write_timeout=100 \
    log_buf_len=1024K \
    bootconfig

BOARD_INIT_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

BOARD_BOOTCONFIG += \
    androidboot.load_modules_parallel=true \
    androidboot.boot_devices=3c400000.ufs

AB_OTA_PARTITIONS += \
    abl \
    bl31 \
    boot \
    cap \
    cpm \
    dbc \
    dbl \
    dram_init_0 \
    dram_init_1 \
    dram_init_2 \
    dram_init_3 \
    dram_init_4 \
    dram_init_5 \
    dram_init_6 \
    dram_init_7 \
    dram_init_8 \
    dram_init_9 \
    dram_phy \
    dtbo \
    gc \
    gdmc \
    gsa_bl1 \
    gsa_fw \
    init_boot \
    modem \
    product \
    pvmfw \
    system \
    system_dlkm \
    system_ext \
    tzsw \
    vbmeta \
    vendor \
    vendor_boot \
    vendor_dlkm \
    vendor_kernel_boot

TARGET_BOARD_INFO_FILE := vendor/google_devices/mustang/firmware/android-info.txt

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/mustang/sepolicy/system_ext/private
PRODUCT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/mustang/sepolicy/product/private
BOARD_VENDOR_SEPOLICY_DIRS += vendor/google_devices/mustang/sepolicy/vendor
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/mustang/sepolicy/system_ext/public
PRODUCT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/mustang/sepolicy/product/public
SELINUX_IGNORE_NEVERALLOWS := true

# BUILD_BROKEN_DUP_RULES is needed for overriding AOSP-available files with extracted prebuilts
BUILD_BROKEN_DUP_RULES := true
