includes:
  - pixel.yml

device:
  platform: laguna

kernel_cmdline_exclusions:
  - init_on_alloc=0
  - init_on_free=1

kernel_cmdline_inclusions:
  - aoc_core.aoc_enable_gsa_boot=1
  - vh_sched.load_sequential=1

sepolicy_inclusions:
  system_ext:
    contexts:
      system_ext_property_contexts:
        - persist.fingerprint.screenprotector.config u:object_r:fingerprint_sp_prop:s0 exact string
  vendor:
    contexts:
      vendor_file_contexts:
        - /(vendor|system/vendor)/bin/etraced u:object_r:etraced_exec:s0
        - /data/vendor/android.hardware.camera.provider@2.7-service-google(/.*)? u:object_r:vendor_camera_data_file:s0
        - /dev/block/by-name/rdbl u:object_r:rdbl_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/abl_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/bl31_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/bl_data u:object_r:vendor_bootlogs_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/boot_[ab] u:object_r:boot_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/cap_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/cpm_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dbc_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dbl_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/devinfo u:object_r:devinfo_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dpm_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_0_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_1_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_2_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_3_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_4_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_5_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_6_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_7_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_8_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_init_9_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_phy_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dram_train_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/dtbo_[ab] u:object_r:dtbo_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/efs u:object_r:efs_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/efs_backup u:object_r:efs_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/frp u:object_r:frp_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/gc_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/gdmc_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/gsa_bl1_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/gsa_fw_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/init_boot_[ab] u:object_r:boot_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/metadata u:object_r:metadata_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/mfg_data u:object_r:mfg_data_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/misc u:object_r:misc_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/modem_[ab] u:object_r:modem_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/modem_userdata u:object_r:modem_userdata_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/persist u:object_r:persist_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/pvmfw_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/super u:object_r:super_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/trusty_persist u:object_r:tee_persist_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/trusty_userdata u:object_r:tee_userdata_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/tzsw_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/ufs_internal u:object_r:ufs_internal_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/userdata u:object_r:userdata_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/vbmeta_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/vbmeta_system_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/vbmeta_vendor_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/vendor_boot_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/block/platform/3c400000\.ufs/by-name/vendor_kernel_boot_[ab] u:object_r:custom_ab_block_device:s0
        - /dev/dri/card[0-9] u:object_r:graphics_device:s0
        - /dev/dri/renderD128 u:object_r:gpu_device:s0
        - /dev/dri/renderD[0-9]* u:object_r:gpu_device:s0
        - /dev/esim_tracer u:object_r:radio_device:s0
        - /dev/iif u:object_r:iif_device:s0
        - /dev/logbuffer_tty1 u:object_r:logbuffer_device:s0
        - /dev/lwis-.* u:object_r:lwis_device:s0
        - /dev/pvr_sync u:object_r:gpu_device:s0
        - /dev/ttyS1 u:object_r:hci_attach_dev:s0
        - /dev/vpu u:object_r:video_device:s0
        - /sys/devices/platform/([0-9A-Fa-f])+.gsa-ns/log_intermediate u:object_r:sysfs_gsa:s0
        - /sys/devices/platform/([0-9A-Fa-f])+.gsa-ns/log_main u:object_r:sysfs_gsa:s0
        - /sys/devices/platform/([0-9A-Fa-f])+.gsa-ns/rom_patch u:object_r:sysfs_gsa:s0
        - /sys/devices/platform/9000000.aoc/.*/wakeup.* u:object_r:sysfs_wakeup:s0
        - /vendor/bin/dump/dump_bootlogs_bldr u:object_r:dump_bootlogs_bldr_exec:s0
        - /vendor/bin/dump/dump_chip_info u:object_r:dump_chip_info_exec:s0
        - /vendor/bin/dump/dump_clocks u:object_r:dump_clocks_exec:s0
        - /vendor/bin/dump/dump_display_userdebug\.sh u:object_r:dump_pixel_display_userdebug_exec:s0
        - /vendor/bin/dump/dump_dwc3\.sh u:object_r:dump_dwc3_exec:s0
        - /vendor/bin/dump/dump_gsa u:object_r:dump_gsa_exec:s0
        - /vendor/bin/dump/dump_interrupts_traces u:object_r:dump_interrupts_traces_exec:s0
        - /vendor/bin/dump/dump_mailbox u:object_r:dump_mailbox_exec:s0
        - /vendor/bin/dump/dump_pixel_display u:object_r:dump_pixel_display_exec:s0
        - /vendor/bin/dump/dump_telemetry u:object_r:dump_telemetry_exec:s0
        - /vendor/bin/dump/dump_uwb u:object_r:dump_uwb_exec:s0
        - /vendor/bin/hw/android\.hardware\.composer\.drm-hwc3-service u:object_r:hal_graphics_composer_default_exec:s0
        - /vendor/bin/hw/android\.hardware\.gatekeeper@1\.0-service\.software u:object_r:hal_gatekeeper_default_exec:s0
        - /vendor/bin/hw/android\.hardware\.health-service\.laguna u:object_r:hal_health_default_exec:s0
        - /vendor/bin/hw/android\.hardware\.samsung\.uwb-service u:object_r:hal_uwb_vendor_default_exec:s0
        - /vendor/bin/hw/google\.hardware\.media\.c2@3\.0-service u:object_r:mediacodec_google_exec:s0
        - /vendor/bin/hw/init.h2omg.sh u:object_r:h2omg_vendor_exec:s0
        - /vendor/bin/hw/init_rdbl\.sh u:object_r:init_rdbl_exec:s0
        - /vendor/bin/hw/pixel\.gralloc\.allocator-V[1-2]-service u:object_r:hal_graphics_allocator_default_exec:s0
        - /vendor/bin/hw/vendor\.google\.plat_security-service u:object_r:hal_plat_security_exec:s0
        - /vendor/bin/pixel_irq_load_balancer u:object_r:pixel_irq_load_balancer_exec:s0
        - /vendor/bin/shared_modem_platform u:object_r:shared_modem_platform_exec:s0
        - /vendor/lib64/hw/android\.hardware\.graphics\.mapper@4\.0-impl-pixel\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/hw/vulkan.powervr\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libcustomer_gralloc_ddk_api\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libedgetpu_litert\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libIMGegl\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libPixelGrallocProperties\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libPVROCL\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libsrv_um\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libufwriter\.so u:object_r:same_process_hal_file:s0
        - /vendor/lib64/libusc\.so u:object_r:same_process_hal_file:s0
        - /vendor/bin/dump/dump_pixel_second_display u:object_r:dump_pixel_second_display_exec:s0
        - /vendor/bin/hw/android\.hardware\.biometrics\.fingerprint-service\.goodix u:object_r:hal_fingerprint_capacitance_exec:s0
        - /vendor/bin/rango_init_thermal_config u:object_r:init_thermal_config_exec:s0

      vendor_property_contexts:
        - persist.vendor.display.primary. u:object_r:vendor_display_prop:s0
        - persist.vendor.pixel_gralloc.compression u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.camera u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.cpu u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.dpu u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.gpu u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.tpu u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.video_decoder u:object_r:vendor_pixel_gralloc_prop:s0
        - persist.vendor.pixel_gralloc.compression.video_encoder u:object_r:vendor_pixel_gralloc_prop:s0
        - ro.vendor.camera. u:object_r:vendor_camera_prop:s0
        - ro.vendor.display. u:object_r:vendor_display_prop:s0
        - ro.vendor.primarydisplay. u:object_r:vendor_display_prop:s0
        - ro.vendor.secondarydisplay. u:object_r:vendor_display_prop:s0
        - vendor.sys.usb.adb.disabled u:object_r:vendor_usb_config_prop:s0

      vendor_service_contexts:
        - com.google.input.ITwoshayFileDumpService/touchflow_default u:object_r:twoshay_file_dump_service:s0
        - com.google.input.ITwoshayFileDumpService/touchflow_outer u:object_r:twoshay_file_dump_service:s0
        - com.google.input.ITwoshayFileDumpService/twoshay u:object_r:twoshay_file_dump_service:s0
        - telephony.oem.oemrilhook u:object_r:radio_service:s0
        - vendor.google.plat_security.ISecureTimestamp/default u:object_r:hal_plat_security_service:s0
        - vendor.google.plat_security.ITrustyDecrypt/default u:object_r:hal_plat_security_service:s0

sysconfig_exclusions:
  - |-
    <permission name="com.google.android.aicore.permission.VENDOR_INTELLIGENCE">
      <group gid="vendor_intelligence"/>
    </permission>
  - <allow-association target="com.google.android.apps.pixel.psi" allowed="com.google.android.as"/>
  - <allow-association target="com.google.android.apps.pixel.psi" allowed="com.google.android.as.oss"/>
  - <allow-association target="com.google.android.apps.pixel.psi" allowed="com.google.android.providers.media.module"/>
  - <allow-association target="com.google.android.apps.pixel.psi" allowed="com.google.android.settings.intelligence"/>
  - <allow-association target="com.google.android.as" allowed="com.google.android.apps.pixel.psi"/>
  - <allow-association target="com.google.android.as.oss" allowed="com.android.systemui"/>
  - <allow-association target="com.google.android.as.oss" allowed="com.google.android.apps.messaging"/>
  - <allow-association target="com.google.android.as.oss" allowed="com.google.android.apps.pixel.psi"/>
  - <allow-association target="com.google.android.as.oss" allowed="com.google.android.apps.pixel.subzero"/>
  - <allow-association target="com.google.android.as.oss" allowed="com.google.android.apps.weather"/>
  - <allow-association target="com.google.android.as.oss" allowed="com.google.android.dialer"/>
  - |-
    <privapp-permissions package="com.android.phone">
      <permission name="android.permission.NETWORK_FACTORY"/>
    </privapp-permissions>

vintf_inclusions:
  - com.google.input.ITwoshayFileDumpService/touchflow_default
  - com.google.input.ITwoshayFileDumpService/touchflow_outer
  - com.google.input.ITwoshayFileDumpService/twoshay
  - vendor.google.plat_security.ISecureTimestamp/default
  - vendor.google.plat_security.ITrustyDecrypt/default

filters:
  file_exclusions:
    match:
      - vendor/bin/storage_intelligence.sh # TODO
      - vendor/etc/init/storage.intelligence.rc # TODO
      - product/wallpaper/image/fallback_green_dark.jpg
      - product/wallpaper/image/fallback_green.jpg
      - product/wallpaper/image/fallback_sterling_dark.jpg
      - product/wallpaper/image/fallback_sterling.jpg
      - product/wallpaper/image/front_green_dark.jpg
      - product/wallpaper/image/front_green.jpg
      - product/wallpaper/image/front_sterling_dark.jpg
      - product/wallpaper/image/front_sterling.jpg
      - product/wallpaper/video/green_dark.mp4
      - product/wallpaper/video/green.mp4
      - product/wallpaper/video/sterling_dark.mp4
      - product/wallpaper/video/sterling.mp4
