kernel_cmdline_exclusions:
  - dyndbg="func alloc_contig_dump_pages +p"
  - init_on_alloc=0
  - init_on_free=1
  - kasan=off
kernel_cmdline_inclusions:
  - android_arch_task_struct_size=512
  - android_arch_task_struct_size=784
  - androidboot.console=ttySAC0
  - aoc_core.aoc_enable_gsa_boot=1
  - aoc_core.aoc_panic_on_ssr_failure=1
  - arm64.nomops
  - arm64.nosme
  - arm_smmu_v3_kvm.atomic_pages=5897
  - arm_smmu_v3_kvm.smc_s2=true
  - at24.write_timeout=100
  - bootconfig
  - cgroup.memory=nokmem
  - cgroup_disable=memory
  - cma_sysfs.experimental=Y
  - console=ttySAC0,115200
  - disable_dma32=on
  - earlycon=exynos4210,0x10870000
  - earlycon=exynos4210,0x10A00000
  - exynos_drm.load_sequential=1
  - exynos_mfc.load_sequential=1
  - fips140.load_sequential=1
  - g2d.load_sequential=1
  - gs_governor_dsulat.async_probe=1
  - log_buf_len=1024K
  - max77779_pmic.load_sequential=1
  - max77779_pmic_pinctrl.load_sequential=1
  - max77779_pmic_spmi.load_sequential=1
  - page_pinner=on
  - panel-samsung-ana6707-f10.load_sequential=1
  - pcie-exynos-core.load_sequential=1
  - pcie_exynos_gs.load_sequential=1
  - printk.devkmsg=on
  - rcu_nocbs=all
  - rcupdate.rcu_expedited=1
  - rcutree.enable_rcu_lazy
  - regmap-goog-spmi.load_sequential=1
  - rodata=on
  - s2mpg12-regulator.load_sequential=1
  - samsung_dma_heap.gcma_skip_heaps=gcma_camera_internal
  - samsung_iommu_v9.load_sequential=1
  - spmi_smartdv.load_sequential=1
  - stack_depot_disable=off
  - swiotlb=1024
  - swiotlb=noforce
  - sysctl.kernel.sched_pelt_multiplier=4
  - ufs.async_probe=1
  - vh_sched.load_sequential=1
  - vh_sched.load_sequential=1
  - vs_drm.async_probe=1
