// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.1
// source: frameworks/base/tools/aapt2/BriefPackageInfo.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "aapt.pb";

export interface BriefPackageInfo {
  packageName: string;
  versionCode: number;
  targetSdk: number;
  /** permission-trees are a part of this list since permission-tree is a subtype of permission */
  permission: string[];
  permissionGroup: string[];
  usesPermission: string[];
  contentProviderAuthority: string[];
  usesLibrary: string[];
  optionalUsesLibrary: string[];
}

function createBaseBriefPackageInfo(): BriefPackageInfo {
  return {
    packageName: "",
    versionCode: 0,
    targetSdk: 0,
    permission: [],
    permissionGroup: [],
    usesPermission: [],
    contentProviderAuthority: [],
    usesLibrary: [],
    optionalUsesLibrary: [],
  };
}

export const BriefPackageInfo: MessageFns<BriefPackageInfo> = {
  encode(message: BriefPackageInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.packageName !== "") {
      writer.uint32(10).string(message.packageName);
    }
    if (message.versionCode !== 0) {
      writer.uint32(16).int64(message.versionCode);
    }
    if (message.targetSdk !== 0) {
      writer.uint32(24).int32(message.targetSdk);
    }
    for (const v of message.permission) {
      writer.uint32(34).string(v!);
    }
    for (const v of message.permissionGroup) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.usesPermission) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.contentProviderAuthority) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.usesLibrary) {
      writer.uint32(66).string(v!);
    }
    for (const v of message.optionalUsesLibrary) {
      writer.uint32(74).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BriefPackageInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBriefPackageInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.packageName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.versionCode = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.targetSdk = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.permission.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.permissionGroup.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.usesPermission.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.contentProviderAuthority.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.usesLibrary.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.optionalUsesLibrary.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BriefPackageInfo {
    return {
      packageName: isSet(object.packageName)
        ? globalThis.String(object.packageName)
        : isSet(object.package_name)
        ? globalThis.String(object.package_name)
        : "",
      versionCode: isSet(object.versionCode)
        ? globalThis.Number(object.versionCode)
        : isSet(object.version_code)
        ? globalThis.Number(object.version_code)
        : 0,
      targetSdk: isSet(object.targetSdk)
        ? globalThis.Number(object.targetSdk)
        : isSet(object.target_sdk)
        ? globalThis.Number(object.target_sdk)
        : 0,
      permission: globalThis.Array.isArray(object?.permission)
        ? object.permission.map((e: any) => globalThis.String(e))
        : [],
      permissionGroup: globalThis.Array.isArray(object?.permissionGroup)
        ? object.permissionGroup.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.permission_group)
        ? object.permission_group.map((e: any) => globalThis.String(e))
        : [],
      usesPermission: globalThis.Array.isArray(object?.usesPermission)
        ? object.usesPermission.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.uses_permission)
        ? object.uses_permission.map((e: any) => globalThis.String(e))
        : [],
      contentProviderAuthority: globalThis.Array.isArray(object?.contentProviderAuthority)
        ? object.contentProviderAuthority.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.content_provider_authority)
        ? object.content_provider_authority.map((e: any) => globalThis.String(e))
        : [],
      usesLibrary: globalThis.Array.isArray(object?.usesLibrary)
        ? object.usesLibrary.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.uses_library)
        ? object.uses_library.map((e: any) => globalThis.String(e))
        : [],
      optionalUsesLibrary: globalThis.Array.isArray(object?.optionalUsesLibrary)
        ? object.optionalUsesLibrary.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.optional_uses_library)
        ? object.optional_uses_library.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: BriefPackageInfo): unknown {
    const obj: any = {};
    if (message.packageName !== "") {
      obj.packageName = message.packageName;
    }
    if (message.versionCode !== 0) {
      obj.versionCode = Math.round(message.versionCode);
    }
    if (message.targetSdk !== 0) {
      obj.targetSdk = Math.round(message.targetSdk);
    }
    if (message.permission?.length) {
      obj.permission = message.permission;
    }
    if (message.permissionGroup?.length) {
      obj.permissionGroup = message.permissionGroup;
    }
    if (message.usesPermission?.length) {
      obj.usesPermission = message.usesPermission;
    }
    if (message.contentProviderAuthority?.length) {
      obj.contentProviderAuthority = message.contentProviderAuthority;
    }
    if (message.usesLibrary?.length) {
      obj.usesLibrary = message.usesLibrary;
    }
    if (message.optionalUsesLibrary?.length) {
      obj.optionalUsesLibrary = message.optionalUsesLibrary;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BriefPackageInfo>, I>>(base?: I): BriefPackageInfo {
    return BriefPackageInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BriefPackageInfo>, I>>(object: I): BriefPackageInfo {
    const message = createBaseBriefPackageInfo();
    message.packageName = object.packageName ?? "";
    message.versionCode = object.versionCode ?? 0;
    message.targetSdk = object.targetSdk ?? 0;
    message.permission = object.permission?.map((e) => e) || [];
    message.permissionGroup = object.permissionGroup?.map((e) => e) || [];
    message.usesPermission = object.usesPermission?.map((e) => e) || [];
    message.contentProviderAuthority = object.contentProviderAuthority?.map((e) => e) || [];
    message.usesLibrary = object.usesLibrary?.map((e) => e) || [];
    message.optionalUsesLibrary = object.optionalUsesLibrary?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
