# Generated by adevtool; do not edit
# For more info, see https://github.com/GrapheneOS/adevtool

include vendor/adevtool/config/mk/google_devices/device/panther/BoardConfig-base.mk

BOARD_SUPER_PARTITION_SIZE := 8531214336
BOARD_SUPER_PARTITION_ERROR_LIMIT := 8006926336
BOARD_SUPER_PARTITION_GROUPS := google_dynamic_partitions
BOARD_GOOGLE_DYNAMIC_PARTITIONS_SIZE := 8527020032
BOARD_GOOGLE_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_dlkm system_ext product vendor vendor_dlkm

BOARD_USES_SYSTEM_DLKMIMAGE := true
TARGET_COPY_OUT_SYSTEM_DLKM := system_dlkm
BOARD_USES_VENDOR_DLKMIMAGE := true
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 0x800000
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_VENDOR_KERNEL_BOOTIMAGE_PARTITION_SIZE := 0x4000000
BOARD_DTBOIMG_PARTITION_SIZE := 0x1000000
BOARD_PVMFWIMAGE_PARTITION_SIZE := 0x100000

BOARD_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

BOARD_KERNEL_CMDLINE += \
    fips140.load_sequential=1 \
    exynos_drm.load_sequential=1 \
    swiotlb=noforce \
    earlycon=exynos4210,0x10A00000 \
    console=ttySAC0,115200 \
    androidboot.console=ttySAC0 \
    printk.devkmsg=on \
    cma_sysfs.experimental=Y \
    rcupdate.rcu_expedited=1 \
    rcu_nocbs=all \
    rcutree.enable_rcu_lazy \
    swiotlb=1024 \
    cgroup.memory=nokmem \
    disable_dma32=on \
    rodata=on \
    at24.write_timeout=100 \
    log_buf_len=1024K \
    android_arch_task_struct_size=512 \
    bootconfig

BOARD_INIT_BOOT_HEADER_VERSION := 4

BOARD_MKBOOTIMG_INIT_ARGS += --header_version $(BOARD_INIT_BOOT_HEADER_VERSION)

BOARD_BOOTCONFIG += \
    androidboot.load_modules_parallel=true \
    androidboot.boot_devices=14700000.ufs

AB_OTA_PARTITIONS += \
    abl \
    bl1 \
    bl2 \
    bl31 \
    boot \
    dtbo \
    gsa \
    init_boot \
    ldfw \
    modem \
    pbl \
    product \
    pvmfw \
    system \
    system_dlkm \
    system_ext \
    tzsw \
    vbmeta \
    vendor \
    vendor_boot \
    vendor_dlkm \
    vendor_kernel_boot

TARGET_BOARD_INFO_FILE := vendor/google_devices/panther/firmware/android-info.txt

SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/panther/sepolicy/system_ext/private
PRODUCT_PRIVATE_SEPOLICY_DIRS += vendor/google_devices/panther/sepolicy/product/private
BOARD_VENDOR_SEPOLICY_DIRS += vendor/google_devices/panther/sepolicy/vendor
SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/panther/sepolicy/system_ext/public
PRODUCT_PUBLIC_SEPOLICY_DIRS += vendor/google_devices/panther/sepolicy/product/public
SELINUX_IGNORE_NEVERALLOWS := true

# needed for overriding AOSP-available files with extracted prebuilts
BUILD_BROKEN_DUP_RULES := true
