// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v7.35.1
// source: frameworks/base/proto/src/apk_parser_config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.android.internal.pm.parsing";

/** Apc stands for "APK parser config" */
export interface ApcPackageConfig {
  usesPermissionsToIgnore: string[];
  flags: number;
}

export enum ApcPackageConfig_Flag {
  /** FLAG_ISOLATE_FROM_GMSCORE_AND_FINSKY - enables bidirectional AppsFilter isolation from GmsCore and Finsky (Play Store) */
  FLAG_ISOLATE_FROM_GMSCORE_AND_FINSKY = 0,
  /** FLAG_ISOLATE_FROM_USER_APPS - enables bidirectional AppsFilter isolation from all user apps */
  FLAG_ISOLATE_FROM_USER_APPS = 1,
  /** FLAG_INCLUDE_AS_UNTRUSTED_APP - makes adevtool include priv-app packages as regular unprivileged packages */
  FLAG_INCLUDE_AS_UNTRUSTED_APP = 2,
  UNRECOGNIZED = -1,
}

export function apcPackageConfig_FlagFromJSON(object: any): ApcPackageConfig_Flag {
  switch (object) {
    case 0:
    case "FLAG_ISOLATE_FROM_GMSCORE_AND_FINSKY":
      return ApcPackageConfig_Flag.FLAG_ISOLATE_FROM_GMSCORE_AND_FINSKY;
    case 1:
    case "FLAG_ISOLATE_FROM_USER_APPS":
      return ApcPackageConfig_Flag.FLAG_ISOLATE_FROM_USER_APPS;
    case 2:
    case "FLAG_INCLUDE_AS_UNTRUSTED_APP":
      return ApcPackageConfig_Flag.FLAG_INCLUDE_AS_UNTRUSTED_APP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ApcPackageConfig_Flag.UNRECOGNIZED;
  }
}

export function apcPackageConfig_FlagToJSON(object: ApcPackageConfig_Flag): string {
  switch (object) {
    case ApcPackageConfig_Flag.FLAG_ISOLATE_FROM_GMSCORE_AND_FINSKY:
      return "FLAG_ISOLATE_FROM_GMSCORE_AND_FINSKY";
    case ApcPackageConfig_Flag.FLAG_ISOLATE_FROM_USER_APPS:
      return "FLAG_ISOLATE_FROM_USER_APPS";
    case ApcPackageConfig_Flag.FLAG_INCLUDE_AS_UNTRUSTED_APP:
      return "FLAG_INCLUDE_AS_UNTRUSTED_APP";
    case ApcPackageConfig_Flag.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface PackageInstallRequirements {
  certSha256: string;
  minVersion: number;
}

export interface ApkParserConfig {
  /** permission name -> package name */
  permissionOwners: { [key: string]: string };
  /** permission group name -> package name */
  permissionGroupOwners: { [key: string]: string };
  /** content provider authority -> package name */
  contentProviderAuthorityOwners: { [key: string]: string };
  /** packages from stock OS that are not allowed to be installed */
  nonInstallablePackages: string[];
  /** map keys are package names */
  parsingConfigs: { [key: string]: ApcPackageConfig };
  /** packages from stock OS that can be installed if requirements are met; map keys are package names */
  installablePackages: { [key: string]: PackageInstallRequirements };
}

export interface ApkParserConfig_PermissionOwnersEntry {
  key: string;
  value: string;
}

export interface ApkParserConfig_PermissionGroupOwnersEntry {
  key: string;
  value: string;
}

export interface ApkParserConfig_ContentProviderAuthorityOwnersEntry {
  key: string;
  value: string;
}

export interface ApkParserConfig_ParsingConfigsEntry {
  key: string;
  value: ApcPackageConfig | undefined;
}

export interface ApkParserConfig_InstallablePackagesEntry {
  key: string;
  value: PackageInstallRequirements | undefined;
}

function createBaseApcPackageConfig(): ApcPackageConfig {
  return { usesPermissionsToIgnore: [], flags: 0 };
}

export const ApcPackageConfig: MessageFns<ApcPackageConfig> = {
  encode(message: ApcPackageConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.usesPermissionsToIgnore) {
      writer.uint32(10).string(v!);
    }
    if (message.flags !== 0) {
      writer.uint32(16).int64(message.flags);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApcPackageConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApcPackageConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.usesPermissionsToIgnore.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.flags = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApcPackageConfig {
    return {
      usesPermissionsToIgnore: globalThis.Array.isArray(object?.usesPermissionsToIgnore)
        ? object.usesPermissionsToIgnore.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.uses_permissions_to_ignore)
        ? object.uses_permissions_to_ignore.map((e: any) => globalThis.String(e))
        : [],
      flags: isSet(object.flags) ? globalThis.Number(object.flags) : 0,
    };
  },

  toJSON(message: ApcPackageConfig): unknown {
    const obj: any = {};
    if (message.usesPermissionsToIgnore?.length) {
      obj.usesPermissionsToIgnore = message.usesPermissionsToIgnore;
    }
    if (message.flags !== 0) {
      obj.flags = Math.round(message.flags);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApcPackageConfig>, I>>(base?: I): ApcPackageConfig {
    return ApcPackageConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApcPackageConfig>, I>>(object: I): ApcPackageConfig {
    const message = createBaseApcPackageConfig();
    message.usesPermissionsToIgnore = object.usesPermissionsToIgnore?.map((e) => e) || [];
    message.flags = object.flags ?? 0;
    return message;
  },
};

function createBasePackageInstallRequirements(): PackageInstallRequirements {
  return { certSha256: "", minVersion: 0 };
}

export const PackageInstallRequirements: MessageFns<PackageInstallRequirements> = {
  encode(message: PackageInstallRequirements, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.certSha256 !== "") {
      writer.uint32(10).string(message.certSha256);
    }
    if (message.minVersion !== 0) {
      writer.uint32(16).int64(message.minVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PackageInstallRequirements {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePackageInstallRequirements();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.certSha256 = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.minVersion = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PackageInstallRequirements {
    return {
      certSha256: isSet(object.certSha256)
        ? globalThis.String(object.certSha256)
        : isSet(object.cert_sha256)
        ? globalThis.String(object.cert_sha256)
        : "",
      minVersion: isSet(object.minVersion)
        ? globalThis.Number(object.minVersion)
        : isSet(object.min_version)
        ? globalThis.Number(object.min_version)
        : 0,
    };
  },

  toJSON(message: PackageInstallRequirements): unknown {
    const obj: any = {};
    if (message.certSha256 !== "") {
      obj.certSha256 = message.certSha256;
    }
    if (message.minVersion !== 0) {
      obj.minVersion = Math.round(message.minVersion);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PackageInstallRequirements>, I>>(base?: I): PackageInstallRequirements {
    return PackageInstallRequirements.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PackageInstallRequirements>, I>>(object: I): PackageInstallRequirements {
    const message = createBasePackageInstallRequirements();
    message.certSha256 = object.certSha256 ?? "";
    message.minVersion = object.minVersion ?? 0;
    return message;
  },
};

function createBaseApkParserConfig(): ApkParserConfig {
  return {
    permissionOwners: {},
    permissionGroupOwners: {},
    contentProviderAuthorityOwners: {},
    nonInstallablePackages: [],
    parsingConfigs: {},
    installablePackages: {},
  };
}

export const ApkParserConfig: MessageFns<ApkParserConfig> = {
  encode(message: ApkParserConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.permissionOwners).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_PermissionOwnersEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    globalThis.Object.entries(message.permissionGroupOwners).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_PermissionGroupOwnersEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    globalThis.Object.entries(message.contentProviderAuthorityOwners).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_ContentProviderAuthorityOwnersEntry.encode({ key: key as any, value }, writer.uint32(26).fork())
        .join();
    });
    for (const v of message.nonInstallablePackages) {
      writer.uint32(34).string(v!);
    }
    globalThis.Object.entries(message.parsingConfigs).forEach(([key, value]: [string, ApcPackageConfig]) => {
      ApkParserConfig_ParsingConfigsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    globalThis.Object.entries(message.installablePackages).forEach(
      ([key, value]: [string, PackageInstallRequirements]) => {
        ApkParserConfig_InstallablePackagesEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
      },
    );
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = ApkParserConfig_PermissionOwnersEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.permissionOwners[entry1.key] = entry1.value;
          }
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = ApkParserConfig_PermissionGroupOwnersEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.permissionGroupOwners[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = ApkParserConfig_ContentProviderAuthorityOwnersEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.contentProviderAuthorityOwners[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nonInstallablePackages.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = ApkParserConfig_ParsingConfigsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.parsingConfigs[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = ApkParserConfig_InstallablePackagesEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.installablePackages[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig {
    return {
      permissionOwners: isObject(object.permissionOwners)
        ? (globalThis.Object.entries(object.permissionOwners) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.permission_owners)
        ? (globalThis.Object.entries(object.permission_owners) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      permissionGroupOwners: isObject(object.permissionGroupOwners)
        ? (globalThis.Object.entries(object.permissionGroupOwners) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.permission_group_owners)
        ? (globalThis.Object.entries(object.permission_group_owners) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      contentProviderAuthorityOwners: isObject(object.contentProviderAuthorityOwners)
        ? (globalThis.Object.entries(object.contentProviderAuthorityOwners) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.content_provider_authority_owners)
        ? (globalThis.Object.entries(object.content_provider_authority_owners) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      nonInstallablePackages: globalThis.Array.isArray(object?.nonInstallablePackages)
        ? object.nonInstallablePackages.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.non_installable_packages)
        ? object.non_installable_packages.map((e: any) => globalThis.String(e))
        : [],
      parsingConfigs: isObject(object.parsingConfigs)
        ? (globalThis.Object.entries(object.parsingConfigs) as [string, any][]).reduce(
          (acc: { [key: string]: ApcPackageConfig }, [key, value]: [string, any]) => {
            acc[key] = ApcPackageConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.parsing_configs)
        ? (globalThis.Object.entries(object.parsing_configs) as [string, any][]).reduce(
          (acc: { [key: string]: ApcPackageConfig }, [key, value]: [string, any]) => {
            acc[key] = ApcPackageConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      installablePackages: isObject(object.installablePackages)
        ? (globalThis.Object.entries(object.installablePackages) as [string, any][]).reduce(
          (acc: { [key: string]: PackageInstallRequirements }, [key, value]: [string, any]) => {
            acc[key] = PackageInstallRequirements.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.installable_packages)
        ? (globalThis.Object.entries(object.installable_packages) as [string, any][]).reduce(
          (acc: { [key: string]: PackageInstallRequirements }, [key, value]: [string, any]) => {
            acc[key] = PackageInstallRequirements.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ApkParserConfig): unknown {
    const obj: any = {};
    if (message.permissionOwners) {
      const entries = globalThis.Object.entries(message.permissionOwners) as [string, string][];
      if (entries.length > 0) {
        obj.permissionOwners = {};
        entries.forEach(([k, v]) => {
          obj.permissionOwners[k] = v;
        });
      }
    }
    if (message.permissionGroupOwners) {
      const entries = globalThis.Object.entries(message.permissionGroupOwners) as [string, string][];
      if (entries.length > 0) {
        obj.permissionGroupOwners = {};
        entries.forEach(([k, v]) => {
          obj.permissionGroupOwners[k] = v;
        });
      }
    }
    if (message.contentProviderAuthorityOwners) {
      const entries = globalThis.Object.entries(message.contentProviderAuthorityOwners) as [string, string][];
      if (entries.length > 0) {
        obj.contentProviderAuthorityOwners = {};
        entries.forEach(([k, v]) => {
          obj.contentProviderAuthorityOwners[k] = v;
        });
      }
    }
    if (message.nonInstallablePackages?.length) {
      obj.nonInstallablePackages = message.nonInstallablePackages;
    }
    if (message.parsingConfigs) {
      const entries = globalThis.Object.entries(message.parsingConfigs) as [string, ApcPackageConfig][];
      if (entries.length > 0) {
        obj.parsingConfigs = {};
        entries.forEach(([k, v]) => {
          obj.parsingConfigs[k] = ApcPackageConfig.toJSON(v);
        });
      }
    }
    if (message.installablePackages) {
      const entries = globalThis.Object.entries(message.installablePackages) as [string, PackageInstallRequirements][];
      if (entries.length > 0) {
        obj.installablePackages = {};
        entries.forEach(([k, v]) => {
          obj.installablePackages[k] = PackageInstallRequirements.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig>, I>>(base?: I): ApkParserConfig {
    return ApkParserConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig>, I>>(object: I): ApkParserConfig {
    const message = createBaseApkParserConfig();
    message.permissionOwners = (globalThis.Object.entries(object.permissionOwners ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.permissionGroupOwners =
      (globalThis.Object.entries(object.permissionGroupOwners ?? {}) as [string, string][]).reduce(
        (acc: { [key: string]: string }, [key, value]: [string, string]) => {
          if (value !== undefined) {
            acc[key] = globalThis.String(value);
          }
          return acc;
        },
        {},
      );
    message.contentProviderAuthorityOwners =
      (globalThis.Object.entries(object.contentProviderAuthorityOwners ?? {}) as [string, string][]).reduce(
        (acc: { [key: string]: string }, [key, value]: [string, string]) => {
          if (value !== undefined) {
            acc[key] = globalThis.String(value);
          }
          return acc;
        },
        {},
      );
    message.nonInstallablePackages = object.nonInstallablePackages?.map((e) => e) || [];
    message.parsingConfigs = (globalThis.Object.entries(object.parsingConfigs ?? {}) as [string, ApcPackageConfig][])
      .reduce((acc: { [key: string]: ApcPackageConfig }, [key, value]: [string, ApcPackageConfig]) => {
        if (value !== undefined) {
          acc[key] = ApcPackageConfig.fromPartial(value);
        }
        return acc;
      }, {});
    message.installablePackages =
      (globalThis.Object.entries(object.installablePackages ?? {}) as [string, PackageInstallRequirements][]).reduce(
        (acc: { [key: string]: PackageInstallRequirements }, [key, value]: [string, PackageInstallRequirements]) => {
          if (value !== undefined) {
            acc[key] = PackageInstallRequirements.fromPartial(value);
          }
          return acc;
        },
        {},
      );
    return message;
  },
};

function createBaseApkParserConfig_PermissionOwnersEntry(): ApkParserConfig_PermissionOwnersEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_PermissionOwnersEntry: MessageFns<ApkParserConfig_PermissionOwnersEntry> = {
  encode(message: ApkParserConfig_PermissionOwnersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_PermissionOwnersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_PermissionOwnersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_PermissionOwnersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_PermissionOwnersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_PermissionOwnersEntry>, I>>(
    base?: I,
  ): ApkParserConfig_PermissionOwnersEntry {
    return ApkParserConfig_PermissionOwnersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_PermissionOwnersEntry>, I>>(
    object: I,
  ): ApkParserConfig_PermissionOwnersEntry {
    const message = createBaseApkParserConfig_PermissionOwnersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseApkParserConfig_PermissionGroupOwnersEntry(): ApkParserConfig_PermissionGroupOwnersEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_PermissionGroupOwnersEntry: MessageFns<ApkParserConfig_PermissionGroupOwnersEntry> = {
  encode(message: ApkParserConfig_PermissionGroupOwnersEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_PermissionGroupOwnersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_PermissionGroupOwnersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_PermissionGroupOwnersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_PermissionGroupOwnersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_PermissionGroupOwnersEntry>, I>>(
    base?: I,
  ): ApkParserConfig_PermissionGroupOwnersEntry {
    return ApkParserConfig_PermissionGroupOwnersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_PermissionGroupOwnersEntry>, I>>(
    object: I,
  ): ApkParserConfig_PermissionGroupOwnersEntry {
    const message = createBaseApkParserConfig_PermissionGroupOwnersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseApkParserConfig_ContentProviderAuthorityOwnersEntry(): ApkParserConfig_ContentProviderAuthorityOwnersEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_ContentProviderAuthorityOwnersEntry: MessageFns<
  ApkParserConfig_ContentProviderAuthorityOwnersEntry
> = {
  encode(
    message: ApkParserConfig_ContentProviderAuthorityOwnersEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_ContentProviderAuthorityOwnersEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_ContentProviderAuthorityOwnersEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_ContentProviderAuthorityOwnersEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_ContentProviderAuthorityOwnersEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_ContentProviderAuthorityOwnersEntry>, I>>(
    base?: I,
  ): ApkParserConfig_ContentProviderAuthorityOwnersEntry {
    return ApkParserConfig_ContentProviderAuthorityOwnersEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_ContentProviderAuthorityOwnersEntry>, I>>(
    object: I,
  ): ApkParserConfig_ContentProviderAuthorityOwnersEntry {
    const message = createBaseApkParserConfig_ContentProviderAuthorityOwnersEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseApkParserConfig_ParsingConfigsEntry(): ApkParserConfig_ParsingConfigsEntry {
  return { key: "", value: undefined };
}

export const ApkParserConfig_ParsingConfigsEntry: MessageFns<ApkParserConfig_ParsingConfigsEntry> = {
  encode(message: ApkParserConfig_ParsingConfigsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      ApcPackageConfig.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_ParsingConfigsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_ParsingConfigsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ApcPackageConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_ParsingConfigsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? ApcPackageConfig.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ApkParserConfig_ParsingConfigsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ApcPackageConfig.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_ParsingConfigsEntry>, I>>(
    base?: I,
  ): ApkParserConfig_ParsingConfigsEntry {
    return ApkParserConfig_ParsingConfigsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_ParsingConfigsEntry>, I>>(
    object: I,
  ): ApkParserConfig_ParsingConfigsEntry {
    const message = createBaseApkParserConfig_ParsingConfigsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ApcPackageConfig.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseApkParserConfig_InstallablePackagesEntry(): ApkParserConfig_InstallablePackagesEntry {
  return { key: "", value: undefined };
}

export const ApkParserConfig_InstallablePackagesEntry: MessageFns<ApkParserConfig_InstallablePackagesEntry> = {
  encode(message: ApkParserConfig_InstallablePackagesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      PackageInstallRequirements.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_InstallablePackagesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_InstallablePackagesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = PackageInstallRequirements.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_InstallablePackagesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? PackageInstallRequirements.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ApkParserConfig_InstallablePackagesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = PackageInstallRequirements.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_InstallablePackagesEntry>, I>>(
    base?: I,
  ): ApkParserConfig_InstallablePackagesEntry {
    return ApkParserConfig_InstallablePackagesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_InstallablePackagesEntry>, I>>(
    object: I,
  ): ApkParserConfig_InstallablePackagesEntry {
    const message = createBaseApkParserConfig_InstallablePackagesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? PackageInstallRequirements.fromPartial(object.value)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
