// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.1
// source: frameworks/base/proto/src/apk_parser_config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.android.internal.pm.parsing";

export interface ApkParsingConfig {
  skipUsesPermission: string[];
  flags: number;
}

export enum ApkParsingConfig_Flag {
  isolate_from_gmscore_and_finsky = 0,
  isolate_from_user_apps = 1,
  include_as_untrusted_app = 2,
  UNRECOGNIZED = -1,
}

export function apkParsingConfig_FlagFromJSON(object: any): ApkParsingConfig_Flag {
  switch (object) {
    case 0:
    case "isolate_from_gmscore_and_finsky":
      return ApkParsingConfig_Flag.isolate_from_gmscore_and_finsky;
    case 1:
    case "isolate_from_user_apps":
      return ApkParsingConfig_Flag.isolate_from_user_apps;
    case 2:
    case "include_as_untrusted_app":
      return ApkParsingConfig_Flag.include_as_untrusted_app;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ApkParsingConfig_Flag.UNRECOGNIZED;
  }
}

export function apkParsingConfig_FlagToJSON(object: ApkParsingConfig_Flag): string {
  switch (object) {
    case ApkParsingConfig_Flag.isolate_from_gmscore_and_finsky:
      return "isolate_from_gmscore_and_finsky";
    case ApkParsingConfig_Flag.isolate_from_user_apps:
      return "isolate_from_user_apps";
    case ApkParsingConfig_Flag.include_as_untrusted_app:
      return "include_as_untrusted_app";
    case ApkParsingConfig_Flag.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ApkParserConfig {
  /** permission name -> package name */
  permissions: { [key: string]: string };
  /** permission group name -> package name */
  permissionGroups: { [key: string]: string };
  /** content provider authority -> package name */
  contentProviderAuthorities: { [key: string]: string };
  /** packages from stock OS that are not allowed to be installed */
  nonInstallablePackages: string[];
  /** key is package name */
  parsingConfigs: { [key: string]: ApkParsingConfig };
  /**
   * packages from stock OS that are allowed to be installed if the certificate digest matches
   * package name -> cert SHA-256 digest
   */
  installablePackages: { [key: string]: string };
}

export interface ApkParserConfig_PermissionsEntry {
  key: string;
  value: string;
}

export interface ApkParserConfig_PermissionGroupsEntry {
  key: string;
  value: string;
}

export interface ApkParserConfig_ContentProviderAuthoritiesEntry {
  key: string;
  value: string;
}

export interface ApkParserConfig_ParsingConfigsEntry {
  key: string;
  value: ApkParsingConfig | undefined;
}

export interface ApkParserConfig_InstallablePackagesEntry {
  key: string;
  value: string;
}

function createBaseApkParsingConfig(): ApkParsingConfig {
  return { skipUsesPermission: [], flags: 0 };
}

export const ApkParsingConfig: MessageFns<ApkParsingConfig> = {
  encode(message: ApkParsingConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.skipUsesPermission) {
      writer.uint32(10).string(v!);
    }
    if (message.flags !== 0) {
      writer.uint32(16).int64(message.flags);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParsingConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParsingConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.skipUsesPermission.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.flags = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParsingConfig {
    return {
      skipUsesPermission: globalThis.Array.isArray(object?.skipUsesPermission)
        ? object.skipUsesPermission.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.skip_uses_permission)
        ? object.skip_uses_permission.map((e: any) => globalThis.String(e))
        : [],
      flags: isSet(object.flags) ? globalThis.Number(object.flags) : 0,
    };
  },

  toJSON(message: ApkParsingConfig): unknown {
    const obj: any = {};
    if (message.skipUsesPermission?.length) {
      obj.skipUsesPermission = message.skipUsesPermission;
    }
    if (message.flags !== 0) {
      obj.flags = Math.round(message.flags);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParsingConfig>, I>>(base?: I): ApkParsingConfig {
    return ApkParsingConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParsingConfig>, I>>(object: I): ApkParsingConfig {
    const message = createBaseApkParsingConfig();
    message.skipUsesPermission = object.skipUsesPermission?.map((e) => e) || [];
    message.flags = object.flags ?? 0;
    return message;
  },
};

function createBaseApkParserConfig(): ApkParserConfig {
  return {
    permissions: {},
    permissionGroups: {},
    contentProviderAuthorities: {},
    nonInstallablePackages: [],
    parsingConfigs: {},
    installablePackages: {},
  };
}

export const ApkParserConfig: MessageFns<ApkParserConfig> = {
  encode(message: ApkParserConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.permissions).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_PermissionsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    globalThis.Object.entries(message.permissionGroups).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_PermissionGroupsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    globalThis.Object.entries(message.contentProviderAuthorities).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_ContentProviderAuthoritiesEntry.encode({ key: key as any, value }, writer.uint32(26).fork())
        .join();
    });
    for (const v of message.nonInstallablePackages) {
      writer.uint32(34).string(v!);
    }
    globalThis.Object.entries(message.parsingConfigs).forEach(([key, value]: [string, ApkParsingConfig]) => {
      ApkParserConfig_ParsingConfigsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    globalThis.Object.entries(message.installablePackages).forEach(([key, value]: [string, string]) => {
      ApkParserConfig_InstallablePackagesEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = ApkParserConfig_PermissionsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.permissions[entry1.key] = entry1.value;
          }
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = ApkParserConfig_PermissionGroupsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.permissionGroups[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = ApkParserConfig_ContentProviderAuthoritiesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.contentProviderAuthorities[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nonInstallablePackages.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = ApkParserConfig_ParsingConfigsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.parsingConfigs[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = ApkParserConfig_InstallablePackagesEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.installablePackages[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig {
    return {
      permissions: isObject(object.permissions)
        ? (globalThis.Object.entries(object.permissions) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      permissionGroups: isObject(object.permissionGroups)
        ? (globalThis.Object.entries(object.permissionGroups) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.permission_groups)
        ? (globalThis.Object.entries(object.permission_groups) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      contentProviderAuthorities: isObject(object.contentProviderAuthorities)
        ? (globalThis.Object.entries(object.contentProviderAuthorities) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.content_provider_authorities)
        ? (globalThis.Object.entries(object.content_provider_authorities) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      nonInstallablePackages: globalThis.Array.isArray(object?.nonInstallablePackages)
        ? object.nonInstallablePackages.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.non_installable_packages)
        ? object.non_installable_packages.map((e: any) => globalThis.String(e))
        : [],
      parsingConfigs: isObject(object.parsingConfigs)
        ? (globalThis.Object.entries(object.parsingConfigs) as [string, any][]).reduce(
          (acc: { [key: string]: ApkParsingConfig }, [key, value]: [string, any]) => {
            acc[key] = ApkParsingConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.parsing_configs)
        ? (globalThis.Object.entries(object.parsing_configs) as [string, any][]).reduce(
          (acc: { [key: string]: ApkParsingConfig }, [key, value]: [string, any]) => {
            acc[key] = ApkParsingConfig.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      installablePackages: isObject(object.installablePackages)
        ? (globalThis.Object.entries(object.installablePackages) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.installable_packages)
        ? (globalThis.Object.entries(object.installable_packages) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ApkParserConfig): unknown {
    const obj: any = {};
    if (message.permissions) {
      const entries = globalThis.Object.entries(message.permissions) as [string, string][];
      if (entries.length > 0) {
        obj.permissions = {};
        entries.forEach(([k, v]) => {
          obj.permissions[k] = v;
        });
      }
    }
    if (message.permissionGroups) {
      const entries = globalThis.Object.entries(message.permissionGroups) as [string, string][];
      if (entries.length > 0) {
        obj.permissionGroups = {};
        entries.forEach(([k, v]) => {
          obj.permissionGroups[k] = v;
        });
      }
    }
    if (message.contentProviderAuthorities) {
      const entries = globalThis.Object.entries(message.contentProviderAuthorities) as [string, string][];
      if (entries.length > 0) {
        obj.contentProviderAuthorities = {};
        entries.forEach(([k, v]) => {
          obj.contentProviderAuthorities[k] = v;
        });
      }
    }
    if (message.nonInstallablePackages?.length) {
      obj.nonInstallablePackages = message.nonInstallablePackages;
    }
    if (message.parsingConfigs) {
      const entries = globalThis.Object.entries(message.parsingConfigs) as [string, ApkParsingConfig][];
      if (entries.length > 0) {
        obj.parsingConfigs = {};
        entries.forEach(([k, v]) => {
          obj.parsingConfigs[k] = ApkParsingConfig.toJSON(v);
        });
      }
    }
    if (message.installablePackages) {
      const entries = globalThis.Object.entries(message.installablePackages) as [string, string][];
      if (entries.length > 0) {
        obj.installablePackages = {};
        entries.forEach(([k, v]) => {
          obj.installablePackages[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig>, I>>(base?: I): ApkParserConfig {
    return ApkParserConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig>, I>>(object: I): ApkParserConfig {
    const message = createBaseApkParserConfig();
    message.permissions = (globalThis.Object.entries(object.permissions ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.permissionGroups = (globalThis.Object.entries(object.permissionGroups ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.contentProviderAuthorities =
      (globalThis.Object.entries(object.contentProviderAuthorities ?? {}) as [string, string][]).reduce(
        (acc: { [key: string]: string }, [key, value]: [string, string]) => {
          if (value !== undefined) {
            acc[key] = globalThis.String(value);
          }
          return acc;
        },
        {},
      );
    message.nonInstallablePackages = object.nonInstallablePackages?.map((e) => e) || [];
    message.parsingConfigs = (globalThis.Object.entries(object.parsingConfigs ?? {}) as [string, ApkParsingConfig][])
      .reduce((acc: { [key: string]: ApkParsingConfig }, [key, value]: [string, ApkParsingConfig]) => {
        if (value !== undefined) {
          acc[key] = ApkParsingConfig.fromPartial(value);
        }
        return acc;
      }, {});
    message.installablePackages = (globalThis.Object.entries(object.installablePackages ?? {}) as [string, string][])
      .reduce((acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseApkParserConfig_PermissionsEntry(): ApkParserConfig_PermissionsEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_PermissionsEntry: MessageFns<ApkParserConfig_PermissionsEntry> = {
  encode(message: ApkParserConfig_PermissionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_PermissionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_PermissionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_PermissionsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_PermissionsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_PermissionsEntry>, I>>(
    base?: I,
  ): ApkParserConfig_PermissionsEntry {
    return ApkParserConfig_PermissionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_PermissionsEntry>, I>>(
    object: I,
  ): ApkParserConfig_PermissionsEntry {
    const message = createBaseApkParserConfig_PermissionsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseApkParserConfig_PermissionGroupsEntry(): ApkParserConfig_PermissionGroupsEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_PermissionGroupsEntry: MessageFns<ApkParserConfig_PermissionGroupsEntry> = {
  encode(message: ApkParserConfig_PermissionGroupsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_PermissionGroupsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_PermissionGroupsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_PermissionGroupsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_PermissionGroupsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_PermissionGroupsEntry>, I>>(
    base?: I,
  ): ApkParserConfig_PermissionGroupsEntry {
    return ApkParserConfig_PermissionGroupsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_PermissionGroupsEntry>, I>>(
    object: I,
  ): ApkParserConfig_PermissionGroupsEntry {
    const message = createBaseApkParserConfig_PermissionGroupsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseApkParserConfig_ContentProviderAuthoritiesEntry(): ApkParserConfig_ContentProviderAuthoritiesEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_ContentProviderAuthoritiesEntry: MessageFns<
  ApkParserConfig_ContentProviderAuthoritiesEntry
> = {
  encode(
    message: ApkParserConfig_ContentProviderAuthoritiesEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_ContentProviderAuthoritiesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_ContentProviderAuthoritiesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_ContentProviderAuthoritiesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_ContentProviderAuthoritiesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_ContentProviderAuthoritiesEntry>, I>>(
    base?: I,
  ): ApkParserConfig_ContentProviderAuthoritiesEntry {
    return ApkParserConfig_ContentProviderAuthoritiesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_ContentProviderAuthoritiesEntry>, I>>(
    object: I,
  ): ApkParserConfig_ContentProviderAuthoritiesEntry {
    const message = createBaseApkParserConfig_ContentProviderAuthoritiesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseApkParserConfig_ParsingConfigsEntry(): ApkParserConfig_ParsingConfigsEntry {
  return { key: "", value: undefined };
}

export const ApkParserConfig_ParsingConfigsEntry: MessageFns<ApkParserConfig_ParsingConfigsEntry> = {
  encode(message: ApkParserConfig_ParsingConfigsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      ApkParsingConfig.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_ParsingConfigsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_ParsingConfigsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ApkParsingConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_ParsingConfigsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? ApkParsingConfig.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ApkParserConfig_ParsingConfigsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ApkParsingConfig.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_ParsingConfigsEntry>, I>>(
    base?: I,
  ): ApkParserConfig_ParsingConfigsEntry {
    return ApkParserConfig_ParsingConfigsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_ParsingConfigsEntry>, I>>(
    object: I,
  ): ApkParserConfig_ParsingConfigsEntry {
    const message = createBaseApkParserConfig_ParsingConfigsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ApkParsingConfig.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseApkParserConfig_InstallablePackagesEntry(): ApkParserConfig_InstallablePackagesEntry {
  return { key: "", value: "" };
}

export const ApkParserConfig_InstallablePackagesEntry: MessageFns<ApkParserConfig_InstallablePackagesEntry> = {
  encode(message: ApkParserConfig_InstallablePackagesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApkParserConfig_InstallablePackagesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApkParserConfig_InstallablePackagesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApkParserConfig_InstallablePackagesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApkParserConfig_InstallablePackagesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApkParserConfig_InstallablePackagesEntry>, I>>(
    base?: I,
  ): ApkParserConfig_InstallablePackagesEntry {
    return ApkParserConfig_InstallablePackagesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApkParserConfig_InstallablePackagesEntry>, I>>(
    object: I,
  ): ApkParserConfig_InstallablePackagesEntry {
    const message = createBaseApkParserConfig_InstallablePackagesEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
